# Config file for Air
# See https://github.com/cosmtrek/air for more details

[build]
  cmd = "go build -o ./tmp/main -buildvcs=false ./cmd/api"
  bin = "./tmp/main"
  full_bin = "set -a && . $(pwd)/.env && set +a && APP_ENV=development ./tmp/main"
  root = "."  # Ensure Air watches the correct root directory
  include_ext = ["go", "tpl", "tmpl", "html", ".env"]
  exclude_dir = ["assets", "tmp", "vendor"]
  follow_symlink = true
  delay = 1000 # ms

[log]
  level = "debug"
  color = true
  timestamp = false

[serve]
  watch_dir = ["."]
  watch_ext = ["go", "tpl", "tmpl", "html", ".env"]
  watch_delay = 200 # ms
  ignore = ["assets", "tmp", "vendor"]
