basePath: /v1
definitions:
  real-time-messaging_consumer_pkg_http.SuccessResponseData:
    properties:
      data: {}
      status:
        description: '"success"'
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API for managing real-time messaging
  title: Real-Time Messaging Consumer API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check if the service is healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/real-time-messaging_consumer_pkg_http.SuccessResponseData'
      summary: Health Check
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
