basePath: /v1
definitions:
  internal_adapters_inbound_rest_v1_handlers.LoginRequest:
    properties:
      email:
        example: john.doe@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
  real-time-messaging_consumer_pkg_http.ErrorResponseData:
    properties:
      error:
        type: string
      status:
        description: '"error"'
        type: string
    type: object
  real-time-messaging_consumer_pkg_http.SuccessResponseData:
    properties:
      data: {}
      status:
        description: '"success"'
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API for managing real-time messaging
  title: Real-Time Messaging Consumer API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/internal_adapters_inbound_rest_v1_handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/real-time-messaging_consumer_pkg_http.SuccessResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/real-time-messaging_consumer_pkg_http.ErrorResponseData'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/real-time-messaging_consumer_pkg_http.ErrorResponseData'
      summary: User login
      tags:
      - auth
  /health:
    get:
      consumes:
      - application/json
      description: Check if the service is healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/real-time-messaging_consumer_pkg_http.SuccessResponseData'
      summary: Health Check
  /v1/ws:
    get:
      description: This endpoint establishes a WebSocket connection but cannot be
        tested via Swagger UI. Use a WebSocket client instead
      responses:
        "101":
          description: Switching Protocols
          schema:
            type: string
      summary: WebSocket Connection
      tags:
      - websocket
      x-hidden: true
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
